plugins {
    id 'java'
}

group 'dev.selenium'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext['seleniumVersion'] = System.getProperty('selenium.version', '4.43.0')

dependencies {
    testImplementation "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"
    testImplementation "org.seleniumhq.selenium:htmlunit3-driver:${seleniumVersion}"
    testImplementation "org.seleniumhq.selenium:selenium-grid:${seleniumVersion}"
    testImplementation platform("org.junit:junit-bom:6.0.2")
    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.platform:junit-platform-suite'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.titusfortner:selenium-logger:2.4.0'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

tasks.register('smokeTest', Test) {
    description = "Runs smoke test suite"
    group = "verification"

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    useJUnitPlatform {
        includeTags 'smoke'
    }

    testLogging {
        events "passed", "skipped", "failed"
    }
}

tasks.register('regressionTest', Test) {
    description = "Runs smoke test suite"
    group = "verification"

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    useJUnitPlatform {
        includeTags 'regression'
    }

    testLogging {
        events "passed", "skipped", "failed"
    }
}

tasks.register('fullTest', Test) {
    description = "Runs full test suite"
    group = "verification"

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    useJUnitPlatform {
        includeTags 'smoke', 'regression'
    }

    testLogging {
        events "passed", "skipped", "failed"
    }
}