plugins {
    id 'java'
}

group 'dev.selenium'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext['seleniumVersion'] = System.getProperty('selenium.version', '4.43.0')

dependencies {
    testImplementation "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"
    testImplementation "org.seleniumhq.selenium:htmlunit3-driver:${seleniumVersion}"
    testImplementation "org.seleniumhq.selenium:selenium-grid:${seleniumVersion}"
    testImplementation platform("org.junit:junit-bom:6.0.2")
    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.platform:junit-platform-suite'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.titusfortner:selenium-logger:2.4.0'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

// Smoke suite task
tasks.register('smokeTest', Test) {
    useJUnitPlatform {
        includeTags 'smoke'
    }
    //systemProperty 'baseUrl', project.findProperty('baseUrl') ?: 'https://staging.example.com'
   // systemProperty 'env', project.findProperty('env') ?: 'staging'
}